export const INITIALISE = 'INITIALISE'

export const FETCH_USER = 'FETCH_USER'

export const CREATE_PLAYER = 'CREATE_PLAYER'
export const CREATE_COMPETITION = 'CREATE_COMPETITION'
export const RECORD_RESULT = 'RECORD_RESULT'
export const REMOVE_RESULT = 'REMOVE_RESULT'
export const RECORD_COMPETITION = 'RECORD_COMPETITION'
export const ENTER_PLAYER = 'ENTER_PLAYER'
